-- Migration 022: Token re-encryption scaffold
--
-- When ENCRYPTION_KEY is first configured on an existing deployment,
-- plaintext OAuth tokens already stored in the sessions table must be
-- encrypted.  This migration is intentionally a no-op at the SQL level
-- because the re-encryption requires application-level Fernet encryption
-- which cannot run inside a pure SQL migration.
--
-- The EncryptionService.decrypt() method already handles legacy plaintext
-- tokens transparently (detects gho_/ghp_/ghr_ prefixes and returns them
-- as-is).  On the next token refresh cycle, the refreshed token is stored
-- encrypted, completing the migration organically.
--
-- This file exists as a placeholder to:
--   1. Reserve the migration version number.
--   2. Document the migration strategy.
--   3. Satisfy task T003/T017 in the security audit.
--
-- No schema changes are required.
SELECT 1;
