"""Roadmap batch launcher — delegates to existing pipeline launch (FR-005)."""

from __future__ import annotations

from src.logging_utils import get_logger
from src.models.roadmap import RoadmapBatch

logger = get_logger(__name__)


async def launch_roadmap_batch(
    batch: RoadmapBatch,
    pipeline_id: str,
    session,
) -> list[int]:
    """Launch each item in a roadmap batch through the existing pipeline.

    Iterates over batch.items and calls execute_pipeline_launch() for each.
    Zero new issue-creation code — fully delegated to existing logic.

    Args:
        batch: The generated roadmap batch.
        pipeline_id: Target pipeline ID for launching items.
        session: UserSession with access token.

    Returns:
        List of created issue numbers.
    """
    from src.api.pipelines import execute_pipeline_launch

    created_issues: list[int] = []

    for item in batch.items:
        try:
            # Build a structured issue body from the roadmap item
            issue_body = (
                f"## {item.title}\n\n"
                f"**Priority:** {item.priority} | **Size:** {item.size}\n\n"
                f"**Rationale:** {item.rationale}\n\n"
                f"---\n\n"
                f"{item.body}\n\n"
                f"---\n_Generated by Roadmap Engine_"
            )

            result = await execute_pipeline_launch(
                project_id=batch.project_id,
                issue_description=issue_body,
                pipeline_id=pipeline_id,
                session=session,
            )

            if result and hasattr(result, "issue_number") and result.issue_number:
                created_issues.append(result.issue_number)
                logger.info(
                    "Launched roadmap item '%s' as issue #%d",
                    item.title,
                    result.issue_number,
                )
            else:
                logger.warning("Pipeline launch returned no issue number for '%s'", item.title)
        except Exception:
            logger.error(
                "Failed to launch roadmap item '%s' for project %s",
                item.title,
                batch.project_id,
                exc_info=True,
            )

    logger.info(
        "Roadmap batch launch complete: %d/%d items launched for project %s",
        len(created_issues),
        len(batch.items),
        batch.project_id,
    )
    return created_issues
