services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - ghchat-dev

networks:
  ghchat-dev:
    driver: bridge
