openapi: 3.0.3
info:
  title: GitHub Project Board API
  description: API endpoints for the real-time GitHub Project Board feature
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1 base path

paths:
  /board/projects:
    get:
      operationId: listBoardProjects
      summary: List available GitHub Projects for board display
      description: |
        Returns all GitHub Projects accessible to the authenticated user,
        including status field configuration for board columns.
      tags:
        - Board
      security:
        - cookieAuth: []
      parameters:
        - name: refresh
          in: query
          description: Force refresh from GitHub API (bypass cache)
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: List of available projects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardProjectListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '503':
          $ref: '#/components/responses/GitHubAPIError'

  /board/projects/{project_id}:
    get:
      operationId: getBoardData
      summary: Get board data for a specific project
      description: |
        Returns all items in the project organized for board display,
        including custom field values (Priority, Size, Estimate) and linked PRs.
      tags:
        - Board
      security:
        - cookieAuth: []
      parameters:
        - name: project_id
          in: path
          description: GitHub Project GraphQL node ID
          required: true
          schema:
            type: string
            example: "PVT_kwDOBWNFuc4AAgab"
        - name: refresh
          in: query
          description: Force refresh from GitHub API (bypass cache)
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Board data with columns and items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardDataResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '503':
          $ref: '#/components/responses/GitHubAPIError'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session

  responses:
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error: "Not authenticated"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error: "Project not found"
    GitHubAPIError:
      description: GitHub API unavailable or rate limited
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            error: "GitHub API rate limit exceeded"
            details:
              retry_after: 60

  schemas:
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
        details:
          type: object
          additionalProperties: true
          description: Additional error details

    BoardProjectListResponse:
      type: object
      required:
        - projects
      properties:
        projects:
          type: array
          items:
            $ref: '#/components/schemas/BoardProject'

    BoardProject:
      type: object
      required:
        - project_id
        - name
        - url
        - owner_login
        - status_field
      properties:
        project_id:
          type: string
          description: GitHub GraphQL node ID
          example: "PVT_kwDOBWNFuc4AAgab"
        name:
          type: string
          description: Project title
          example: "Development Board"
        description:
          type: string
          nullable: true
          description: Project short description
        url:
          type: string
          format: uri
          description: GitHub project URL
          example: "https://github.com/users/octocat/projects/1"
        owner_login:
          type: string
          description: Owner username or organization
          example: "octocat"
        status_field:
          $ref: '#/components/schemas/StatusField'

    StatusField:
      type: object
      required:
        - field_id
        - options
      properties:
        field_id:
          type: string
          description: GraphQL node ID for the Status field
          example: "PVTSSF_lADOBWNFuc4AAqzszgMgNRU"
        options:
          type: array
          items:
            $ref: '#/components/schemas/StatusOption'

    StatusOption:
      type: object
      required:
        - option_id
        - name
        - color
      properties:
        option_id:
          type: string
          description: Unique option identifier
          example: "f75ad846"
        name:
          type: string
          description: Status display name
          example: "In Progress"
        color:
          $ref: '#/components/schemas/StatusColor'
        description:
          type: string
          nullable: true
          description: Optional status description
          example: "Work actively being done"

    StatusColor:
      type: string
      enum:
        - GRAY
        - BLUE
        - GREEN
        - YELLOW
        - ORANGE
        - RED
        - PINK
        - PURPLE
      description: GitHub predefined status colors

    BoardDataResponse:
      type: object
      required:
        - project
        - columns
      properties:
        project:
          $ref: '#/components/schemas/BoardProject'
        columns:
          type: array
          description: Board columns with their items
          items:
            $ref: '#/components/schemas/BoardColumn'

    BoardColumn:
      type: object
      required:
        - status
        - items
        - item_count
        - estimate_total
      properties:
        status:
          $ref: '#/components/schemas/StatusOption'
        items:
          type: array
          items:
            $ref: '#/components/schemas/BoardItem'
        item_count:
          type: integer
          description: Total items in this column
          example: 5
        estimate_total:
          type: number
          format: float
          description: Sum of estimates for items in this column
          example: 8.5

    BoardItem:
      type: object
      required:
        - item_id
        - content_type
        - title
        - status
        - status_option_id
        - assignees
        - linked_prs
      properties:
        item_id:
          type: string
          description: Project item GraphQL ID
          example: "PVTI_lADOBWNFuc4AAqzszgJcNRU"
        content_id:
          type: string
          nullable: true
          description: Underlying issue/PR GraphQL ID
        content_type:
          $ref: '#/components/schemas/ContentType'
        title:
          type: string
          description: Issue/PR title
          example: "Add project board feature"
        number:
          type: integer
          nullable: true
          description: Issue/PR number (null for drafts)
          example: 164
        repository:
          $ref: '#/components/schemas/Repository'
          nullable: true
        url:
          type: string
          format: uri
          nullable: true
          description: GitHub URL
          example: "https://github.com/octocat/repo/issues/164"
        body:
          type: string
          nullable: true
          description: Issue body/description
        status:
          type: string
          description: Current status name
          example: "In Progress"
        status_option_id:
          type: string
          description: Status option ID
        assignees:
          type: array
          items:
            $ref: '#/components/schemas/Assignee'
        priority:
          $ref: '#/components/schemas/CustomFieldValue'
          nullable: true
        size:
          $ref: '#/components/schemas/CustomFieldValue'
          nullable: true
        estimate:
          type: number
          format: float
          nullable: true
          description: Estimate value (numeric)
          example: 2.5
        linked_prs:
          type: array
          items:
            $ref: '#/components/schemas/LinkedPR'

    ContentType:
      type: string
      enum:
        - issue
        - draft_issue
        - pull_request

    Repository:
      type: object
      required:
        - owner
        - name
      properties:
        owner:
          type: string
          description: Repository owner
          example: "octocat"
        name:
          type: string
          description: Repository name
          example: "github-workflows"

    Assignee:
      type: object
      required:
        - login
        - avatar_url
      properties:
        login:
          type: string
          description: GitHub username
          example: "octocat"
        avatar_url:
          type: string
          format: uri
          description: Avatar image URL
          example: "https://avatars.githubusercontent.com/u/583231?v=4"

    CustomFieldValue:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Field value name
          example: "P1"
        color:
          $ref: '#/components/schemas/StatusColor'
          nullable: true

    LinkedPR:
      type: object
      required:
        - pr_id
        - number
        - title
        - state
        - url
      properties:
        pr_id:
          type: string
          description: PR GraphQL ID
        number:
          type: integer
          description: PR number
          example: 165
        title:
          type: string
          description: PR title
          example: "Implement project board UI"
        state:
          $ref: '#/components/schemas/PRState'
        url:
          type: string
          format: uri
          description: PR URL
          example: "https://github.com/octocat/repo/pull/165"

    PRState:
      type: string
      enum:
        - open
        - closed
        - merged
